from model.transformer import transformer_base, transformer_large, transformer_base_architecture
from model.transformer_gan import transformer_gan
from .hippop_task import HippopTask
from .gan_translation_task import GanHippopTranslationTask